ci: Make able to run workflow in forks with uppercase in names (#782)
### Description of your changes

Deal with

```
ERROR: invalid tag "ghcr.io/MaxymVlasov/pre-commit-terraform-712:latest": repository name must be lowercase
```

Found during testing changes for OSSF score improvement - as I need to test all workflows without disrupting main repo 

---------

Co-authored-by: George L. Yermulnik <yz@yz.kiev.ua>